### ISSUE TITLE
Publish Deck 

### ISSUE THREAD

**Issue by austin-garrard** [translation-cards/txc-maker#12]
*As a humanitarian worker creating a Translation Cards Deck
I want to publish my Deck to a publicly accessible URL
So that I can easily distribute the deck I've made*

**Notes**
- The Preview Screens are the Deck Info Screen and the Translations Screen

**Acceptance Criteria**
- [x] When I view a Preview Screen
Then there is a Publish Deck button (see Preview Screen mocks for placement/styling)

- [x] When I click the Publish Deck button 
Then I am directed to the Share Deck Screen

- [x] When I click the Publish Deck button
Then the Deck is finalized and made available for download at a short URL

- [x] When I view the Share Deck Screen
Then the Deck Card for that deck is displayed

- [x] When I view the Share Deck Screen
Then the URL is displayed 

![share deck](https://cloud.githubusercontent.com/assets/838585/16709341/7fa17892-45d3-11e6-9af5-00d62660bad2.png)

**Comment by benridge** [comment]
testing comment
