### ISSUE TITLE
Invalid deck import warning

### ISSUE THREAD

**Issue by natashaj7** [translation-cards/txc-maker#18]
As a deck creator
I want to be told when I have a input invalid deck information
So that I know what to fix and why the submit button is not working  

- [x] Error check document ID to make sure it points to a valid file 
- [x] Error check audio file id's for valid directory & valid file types
- [x] Display errors beside appropriate fields

**Note** 
- Don't allow user to Preview if errors

**Comment by austin-garrard** [comment]
File types will be checked when actually processing the deck contents. Errors are displayed at top of page, UX concerns such as placement next to fields will be addressed after meeting with Olly to  discuss specifics.
