### ISSUE TITLE
Remove Deck Id field

### ISSUE THREAD

**Issue by austin-garrard** [translation-cards/txc-maker#35]
Per discussions with Olly and Nick, this field should not exist in a user-facing manner. It should be removed from the form, and perhaps removed from the model if there isn't a need for a generated ID field moving forward.

**Comment by austin-garrard** [comment]
In the code, this field is being used to store the client session id, which is the deck's identifier as of now.

**Comment by DeuceTheCoder** [comment]
Field is removed!
