### ISSUE TITLE
Terminate channel connection

### ISSUE THREAD

**Issue by austin-garrard** [translation-cards/txc-maker#50]
The socket that the client opens to the server via the Channel API is never closed. Both the client and the server give errors because they think the channel is still open. 

It should be closed when:
- [x] the Deck Publish Screen is fully loaded and displayed.
- [x] the Deck Preview Screen is fully loaded and displayed with errors that prevent publishing

**Comment by austin-garrard** [comment]
@benridge Consider closing the channel after the needed data has been received. For each page where this is used (Preview and Publish), only one piece of data is sent over the channel. If it is possible to open a new channel for the Publish page, it might be better to use two short-lived channels instead of one persistent one.

**Comment by DeuceTheCoder** [comment]
Tested on dev. I no longer see calls in the browser network inspector. Looks good!
