### ISSUE TITLE
Properly display unicode

### ISSUE THREAD

**Issue by austin-garrard** [translation-cards/txc-maker#52]
This issue only appears on the dev server. Locally, I have not reproduced it.

Have a translation defined as such:

| Language | Label | Translation | Filename |
| --- | --- | --- | --- |
| ar | hello | حددوا نقطة التقاء في هذا الموقع مع أطفالكم وأسرتكم في حال انفصلتم عن بعضكم | FL16-ar.mp3 |
1. Import the deck
2. On the Deck Preview, see this:
   <img width="721" alt="screen shot 2016-08-24 at 11 00 33 am" src="https://cloud.githubusercontent.com/assets/838585/17938058/0d3799e0-69ea-11e6-93e2-0caccd169fe4.png">

**Comment by DeuceTheCoder** [comment]
Now working with the arabic text
