### ISSUE TITLE
Finalize Import Data Screen UX

### ISSUE THREAD

**Issue by austin-garrard** [translation-cards/txc-maker#6]
The functionality for the import data screen is complete:
 - Deck meta data is entered
 - Location of audio and text translations is entered
 - Upon submitting, a TXC is generated and placed in the audio folder

But the page doesn't completely match the spec. 

Acceptance Criteria
- [x] Given I am entering data into the form
When I interact with any field
Then there is a clear explanation of what information is required

- [x]  Given I am interacting with the License URL field
Then there are radio buttons for the Creative Commons license and for a text field to enter a URL

- [x] Given I am entering data into the form
Then the fields should have consistent spacing and formatting

![import deck](https://cloud.githubusercontent.com/assets/838585/16709041/cd8cc556-45ca-11e6-91c7-f8fb4b198188.png)

**Comment by austin-garrard** [comment]
The form UI as of b048db5 has been OK'd by Olly except for the items listed in #43 which will be addressed there.

**Comment by DeuceTheCoder** [comment]
The Document ID and Audio Directory ID fields seem to have misleading explanation text. They both say to use the URL of the Directory/Document, but neither of them accept the actual URL.

**Comment by DeuceTheCoder** [comment]
URLs and IDs now both work. Looks good.
